import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { Parallax, ParallaxLayer } from "@react-spring/parallax"
import devu from "./../src/imgs/devu.jpg"


export default function Home(props) {
  const [isRaining, setIsRaining] = useState(false);
  const [rainStyle, setRainStyle] = useState(styles.container);

  const _ = require("lodash");
  let url = "https://ipapi.co/2a02:2f04:c40d:6100:1155:c13b:a5db:73bc/json/";
  let lat = 0;
  let long = 0;
  let weather = "poateploua";
  let vreme = "mayberain";
  fetch(url)
    .then((res) => res.json())
    .then((out) => {
      console.log(out);
      lat = _.get(out, "latitude", null);
      long = _.get(out, "longitude", null);
      return fetch(
        "https://api.openweathermap.org/data/2.5/weather?lat=" +
          lat +
          "&lon=" +
          long +
          "&appid=5667d20d425ea4533bdbc1d9e3ec3962"
      )
        .then((res) => res.json())
        .then((out) => {
          console.log(out);
          weather = _.get(out, "weather", null);
          console.log(weather);
          vreme = _.get(weather[0], "main", null);
          console.log("Vremea este" + vreme);
          if (vreme === "Rain") 
          {
            setIsRaining(true);
            setRainStyle(styles.container_ploaie); 
          }
        })
          .catch((err) => error);
    })
    .catch((err) => error);
  console.log(lat);
  console.log(long);
  url =
    "https://api.openweathermap.org/data/2.5/weather?lat=" +
    lat +
    "&lon=" +
    long +
    "&appid=5667d20d425ea4533bdbc1d9e3ec3962";

  return (
    <div className={rainStyle}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Parallax pages={2} style={{ top: '0', left: '0' }}>
          <ParallaxLayer
            offset={0}
            speed={-1}
            style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
            <h1 className={styles.title}>Afara ploua?</h1>
          </ParallaxLayer>

          <ParallaxLayer offset={1} speed={2} style={{ backgroundImage: `url(${devu})`, backgroundColor: '#ff6d6d' }} />

          <ParallaxLayer
            offset={1}
            speed={0.5}
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              color: 'white',
            }}>
            <p className={styles.oprisan}>
              {isRaining ? "Da" : "Nu"}
            </p>
          </ParallaxLayer>
        </Parallax>
      </main>
    </div>
  );
}
